pipeline {
    agent any
    tools {
        nodejs 'nodejs_20_12_0' // Configura la versión de Node.js instalada en Jenkins
    }
    stages {
        stage('Install Dependencies') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Chimary7/prestabanco_Frontend']])
                dir('PrestaBanco-Frontend') { // Cambia al directorio 'frontend'
                    bat 'npm install' // Usa 'bat' para Windows o 'sh' para Linux/Mac
                }
            }
        }

        stage('Build Project') {
            steps {
                dir('PrestaBanco-Frontend') { // Cambia al directorio 'frontend'//////
                    bat 'npm run build' // Genera la versión de producción del frontend
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('PrestaBanco-Frontend') { // Cambia al directorio 'frontend'
                        bat 'docker build -t chimary/entregafrontend:latest .' // Construye la imagen Docker
                    }
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'tingeso', variable: 'dhpsw')]) {
                        bat 'docker login -u chimary -p Vd89014545'
                    }
                    bat 'docker push chimary/entregafrontend:latest'
                }
            }
        }
    }
}